package SimuladorAutomovil.gui;

import SimuladorAutomovil.Classes.Simulador;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel David López Sarabia
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Simulador simulador;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    //este metodo se utiliza para cambiar el icono de un label usando la ruta de la imagen
    public static void cambiarIconoDeLabel(JLabel label, String rutaImagen) {
        try {
            // Cargar la imagen desde el archivo en la ruta especificada
            ImageIcon icono = new ImageIcon(rutaImagen);

            // Obtener el tamaño del JLabel
            int ancho = label.getWidth();
            int alto = label.getHeight();

            // Escalar la imagen al tamaño del JLabel
            Image imagen = icono.getImage();
            Image nuevaImagen = imagen.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

            // Crear un ImageIcon a partir de la imagen escalada
            ImageIcon iconoEscalado = new ImageIcon(nuevaImagen);

            // Establecer el nuevo icono en el JLabel
            label.setIcon(iconoEscalado);
        } catch (Exception e) {
            e.printStackTrace();
            // Manejar cualquier excepción que pueda ocurrir al cargar la imagen
            JOptionPane.showMessageDialog(null, "Error al cargar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bEncender = new javax.swing.JButton();
        bAcelerar = new javax.swing.JButton();
        bApagar = new javax.swing.JButton();
        bFrenar = new javax.swing.JButton();
        tTablero = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bSalir = new javax.swing.JButton();
        Auto = new javax.swing.JLabel();
        lVelocidad = new javax.swing.JLabel();
        lLlantas = new javax.swing.JLabel();
        lMotor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SimuladorAutomovil/img/Extreme driving experience.png"))); // NOI18N

        bEncender.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        bEncender.setForeground(new java.awt.Color(102, 0, 0));
        bEncender.setText("Encender");
        bEncender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEncenderActionPerformed(evt);
            }
        });

        bAcelerar.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        bAcelerar.setForeground(new java.awt.Color(102, 0, 0));
        bAcelerar.setText("Acelerar");
        bAcelerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcelerarActionPerformed(evt);
            }
        });

        bApagar.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        bApagar.setForeground(new java.awt.Color(102, 0, 0));
        bApagar.setText("Apagar");
        bApagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApagarActionPerformed(evt);
            }
        });

        bFrenar.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        bFrenar.setForeground(new java.awt.Color(102, 0, 0));
        bFrenar.setText("Frenar");
        bFrenar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFrenarActionPerformed(evt);
            }
        });

        tTablero.setBackground(new java.awt.Color(0, 0, 0));
        tTablero.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        tTablero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTablero.setText(".");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SimuladorAutomovil/img/pngtree-fire-flame-transparent-image-png-image_6707051 1.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SimuladorAutomovil/img/pngtree-fire-flame-transparent-image-png-image_6707051 1.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SimuladorAutomovil/img/pngtree-fire-flame-transparent-image-png-image_6707051 1.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SimuladorAutomovil/img/pngtree-fire-flame-transparent-image-png-image_6707051 1.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SimuladorAutomovil/img/pngtree-fire-flame-transparent-image-png-image_6707051 1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bFrenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAcelerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(bEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bSalir.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        bSalir.setForeground(new java.awt.Color(51, 0, 0));
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        Auto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SimuladorAutomovil/img/auto.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(267, 267, 267))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(Auto))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lMotor, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(lLlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 127, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Auto)
                .addGap(49, 49, 49)
                .addComponent(lLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSalir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setSimulador(Simulador simulador) {
            this.simulador = simulador;
        }
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed
    
    /**
     * Metodo que describe la funcionalidad del botón frenar
     * @param evt el evento de presionar el botón
     */
    private void bEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEncenderActionPerformed
        // TODO add your handling code here:
        String mensaje = simulador.enceder();
        if(mensaje.equals("Su auto ha encendido")){
            mostrarVelocidad();
            tTablero.setText(mensaje);
        }
        else{
            mostrarVelocidad();
            JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        if(simulador.isAccidentado()){
            cambiarIconoDeLabel(Auto, "/home/sam/NetBeansProjects/Simulador/SimuladorAutomovil/src/SimuladorAutomovil/img/auto_accidentado.png");
        }
        else{
            cambiarIconoDeLabel(Auto, "/home/sam/NetBeansProjects/Simulador/SimuladorAutomovil/src/SimuladorAutomovil/img/auto_encendido.png");
        }
    }//GEN-LAST:event_bEncenderActionPerformed

    private void bApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApagarActionPerformed
        // TODO add your handling code here:
        String mensaje = simulador.apagar();
        if(mensaje.equals("Su auto se ha apagado")){
            lVelocidad.setText("");
            tTablero.setText(mensaje);
        }
        else{
            lVelocidad.setText("");
            JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        if(simulador.isAccidentado()){
            cambiarIconoDeLabel(Auto, "/home/sam/NetBeansProjects/Simulador/SimuladorAutomovil/src/SimuladorAutomovil/img/auto_accidentado.png");
        }
        else{
            cambiarIconoDeLabel(Auto, "/home/sam/NetBeansProjects/Simulador/SimuladorAutomovil/src/SimuladorAutomovil/img/auto.png");
        }
    }//GEN-LAST:event_bApagarActionPerformed

    private void bAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcelerarActionPerformed
        // TODO add your handling code here:
        try{
            String intensidad = JOptionPane.showInputDialog(this, "Por favor, ingresa la intensidad: ");
            String[] mensaje = simulador.acelerar(Double.parseDouble(intensidad));
            if(mensaje[0].equals("El auto ha acelerado")){
                mostrarVelocidad();
                tTablero.setText(mensaje[0]);
            }
            else{
                tTablero.setText(mensaje[1]);
                JOptionPane.showMessageDialog(this, mensaje[0], "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            if(simulador.isAccidentado()){
                cambiarIconoDeLabel(Auto, "/home/sam/NetBeansProjects/Simulador/SimuladorAutomovil/src/SimuladorAutomovil/img/auto_accidentado.png");
            }
            else if(!simulador.isEncendido()){
                cambiarIconoDeLabel(Auto, "/home/sam/NetBeansProjects/Simulador/SimuladorAutomovil/src/SimuladorAutomovil/img/auto.png");
            }
            else{
                cambiarIconoDeLabel(Auto, "/home/sam/NetBeansProjects/Simulador/SimuladorAutomovil/src/SimuladorAutomovil/img/auto_acelerando.png");
            }
        }
        catch(NullPointerException e){
            System.out.println("Cerraste el dialogo o algo así");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debes ingresar un numero valido", "ERROR", JOptionPane.ERROR_MESSAGE);
            bAcelerarActionPerformed(evt);
        }
    }//GEN-LAST:event_bAcelerarActionPerformed

    private void bFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFrenarActionPerformed
        // TODO add your handling code here:
        try{
            String intensidad = JOptionPane.showInputDialog(this, "Por favor, ingresa la intensidad:");
            String[] mensaje = simulador.frenar(Double.parseDouble(intensidad));
            if(mensaje[0].equals("Se ha frenado con exito")){
                mostrarVelocidad();
                tTablero.setText(mensaje[0]);
            }
            else{
                tTablero.setText(mensaje[1]);
                JOptionPane.showMessageDialog(this, mensaje[0], "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            if(simulador.isAccidentado()){
                cambiarIconoDeLabel(Auto, "/home/sam/NetBeansProjects/Simulador/SimuladorAutomovil/src/SimuladorAutomovil/img/auto_accidentado.png");
            }
            else{
                cambiarIconoDeLabel(Auto, "/home/sam/NetBeansProjects/Simulador/SimuladorAutomovil/src/SimuladorAutomovil/img/auto.png");
            }
        }
        catch(NullPointerException e){
            System.out.println("Cerraste el dialogo o algo así");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debes ingresar un numero valido", "ERROR", JOptionPane.ERROR_MESSAGE);
            bFrenarActionPerformed(evt);
        }
    }//GEN-LAST:event_bFrenarActionPerformed
    
    public void mostrarVelocidad(){
        lVelocidad.setText("Velocidad: "+simulador.getVehiculo().getVelocidad());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Simulador simulador = new Simulador(MAXIMIZED_BOTH, PROPERTIES);
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setSimulador(simulador);
        ventana.lLlantas.setText("Limite de las llantas: "+simulador.getVehiculo().getLlantas().getLimite());
        ventana.lMotor.setText("Limite del motor: "+simulador.getVehiculo().getMotor().getVelocidadMaxima());
        ventana.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Auto;
    private javax.swing.JButton bAcelerar;
    private javax.swing.JButton bApagar;
    private javax.swing.JButton bEncender;
    private javax.swing.JButton bFrenar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lLlantas;
    private javax.swing.JLabel lMotor;
    private javax.swing.JLabel lVelocidad;
    private javax.swing.JLabel tTablero;
    // End of variables declaration//GEN-END:variables

}